# Generated by Django 5.0.2 on 2025-06-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_follow_up_company_meeting_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow_up',
            options={'verbose_name_plural': '4. Follow_Up'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name_plural': '2. Today Visit'},
        ),
    ]
