# Generated by Django 5.0.2 on 2025-06-27 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_agencies_description'),
        ('utility', '0009_remove_locality_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='locality_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.locality'),
        ),
    ]
