# Generated by Django 5.0.2 on 2025-07-06 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_visit_locality_city'),
        ('utility', '0012_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.visit_status'),
        ),
    ]
