# Generated by Django 5.0.2 on 2025-07-30 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_meta_response_respone_meeting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meta_response',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meta_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meta_response',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_meta_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
