# Generated by Django 5.0.2 on 2025-08-04 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_agencies_created_by_agencies_updated_by'),
        ('utility', '0017_business_type_call_status_requirent_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponeFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('follow_up', models.DateTimeField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('locality_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.locality')),
                ('respone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.meta_response')),
            ],
            options={
                'verbose_name_plural': '7. Respone Follow Up',
            },
        ),
    ]
