# Generated by Django 5.0.1 on 2024-01-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Residential_Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Commencement_Certificate',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Occupancy_Certificate',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True),
        ),
    ]
