# Generated by Django 5.0.2 on 2025-04-18 19:11

import django.db.models.deletion
import mptt.fields
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utility', '0006_delete_bathroom_delete_bedroom_delete_bolconis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('1 RK Studio Apartment', '1 RK Studio Apartment'), ('Flat/Apartment', 'Flat/Apartment'), ('Independent Builder Floor', 'Independent Builder Floor'), ('Independent House Villa', 'Independent House Villa'), ('Villa/Bungalows ', 'Villa/Bungalows '), ('Agricultural Farm Land', 'Agricultural Farm Land'), ('Farm House', 'Farm House')], max_length=55)),
                ('title', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=255)),
                ('meta_description', models.CharField(max_length=255)),
                ('price', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=15000, null=True)),
                ('amenities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Air Condition', 'Air Condition'), ('Badminton Court', 'Badminton Court'), ('balcony', 'balcony'), ('Barbeque', 'Barbeque'), ('Basket Ball', 'Basket Ball'), ('Car Parking', 'Car Parking'), ('CCTV', 'CCTV'), ('club house', 'club house'), ('Community hall', 'Community hall'), ('Conference room', 'Conference room'), ('Creche Area', 'Creche Area'), ('Cricket Pitch', 'Cricket Pitch'), ('Curtains', 'Curtains'), ('Dining Table', 'Dining Table'), ('Electric Vehicle Charging Socket', 'Electric Vehicle Charging Socket'), ('Electrical Switchboard', 'Electrical Switchboard'), ('Elevator', 'Elevator'), ('Exhaust Fan', 'Exhaust Fan'), ('Fans', 'Fans'), ('Fire Fighting Equipment', 'Fire Fighting Equipment'), ('Garden', 'Garden'), ('Geysers', 'Geysers'), ('Grand lobby', 'Grand lobby'), ('Gymnasium', 'Gymnasium'), ('Hammock', 'Hammock'), ('Indoor Games', 'Indoor Games'), ('Intercom', 'Intercom'), ('jacuzzi', 'jacuzzi'), ('Jogging track', 'Jogging track'), ('Kids Play Area', 'Kids Play Area'), ('Library', 'Library'), ('Lights', 'Lights'), ('Live chess', 'Live chess'), ('Microwave', 'Microwave'), ('mini theater', 'mini theater'), ('Modular Kitchen', 'Modular Kitchen'), ('Multipurpose Hall', 'Multipurpose Hall'), ('Rain Water Harvesting', 'Rain Water Harvesting'), ('Reflexology Path', 'Reflexology Path'), ('Refrigerator', 'Refrigerator'), ('Regular Water Supply', 'Regular Water Supply'), ('Rooftop garden', 'Rooftop garden'), ('sauna bath', 'sauna bath'), ('Security', 'Security'), ('Senior citizen area', 'Senior citizen area'), ('Society Office', 'Society Office'), ('Sofa', 'Sofa'), ('Solar Power', 'Solar Power'), ('Spa', 'Spa'), ('Squash court', 'Squash court'), ('Stainless Steel Sink', 'Stainless Steel Sink'), ('Stove', 'Stove'), ('Swimming Pool', 'Swimming Pool'), ('Terrace', 'Terrace'), ('Video Door phone', 'Video Door phone'), ('Volleyball Court', 'Volleyball Court'), ('Wardrobe T.V', 'Wardrobe T.V'), ('Washing Machine', 'Washing Machine'), ('Water Purifier', 'Water Purifier'), ('Water Softener', 'Water Softener'), ('Wi fi', 'Wi fi'), ('yoga deck', 'yoga deck')], max_length=50, null=True)),
                ('project_size', models.CharField(blank=True, max_length=255, null=True)),
                ('possession', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('featured_property', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=55, null=True)),
                ('slug', models.SlugField(blank=True, max_length=555, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.city')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.locality')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='residential.resell')),
            ],
            options={
                'verbose_name_plural': '1. ReSell Property',
            },
        ),
        migrations.CreateModel(
            name='ReSell_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('rate', models.IntegerField(default=1)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='New', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.resell')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '2. ReSell Comment',
            },
        ),
        migrations.CreateModel(
            name='ReSell_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.resell')),
            ],
            options={
                'verbose_name_plural': '3. Sell Images',
            },
        ),
    ]
