# Generated by Django 5.0.2 on 2025-07-19 16:14

import django.db.models.deletion
import mptt.fields
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utility', '0014_delete_possession_in'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=255)),
                ('meta_description', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('1 RK Studio Apartment', '1 RK Studio Apartment'), ('Flat/Apartment', 'Flat/Apartment'), ('Independent Builder Floor', 'Independent Builder Floor'), ('Independent House Villa', 'Independent House Villa'), ('Villa/Bungalows ', 'Villa/Bungalows '), ('Agricultural Farm Land', 'Agricultural Farm Land'), ('Farm House', 'Farm House')], max_length=55)),
                ('title', models.CharField(max_length=150)),
                ('age_of_properties', models.CharField(blank=True, choices=[(' under construction', ' under construction'), ('0 To 5 Years', '0 To 5 Years'), ('5 TO 10 Years', '5 TO 10 Years'), ('10 To 15 Years', '10 To 15 Years'), ('15 To 20 Years', '15 To 20 Years'), ('20 To 25 Years', '20 To 25 Years')], max_length=55, null=True)),
                ('possession', models.DateField(blank=True, null=True)),
                ('price', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('area_type', models.CharField(blank=True, choices=[('Square Feet', 'Square Feet'), ('Square Meter', 'Square Meter'), ('Square Yard', 'Square Yard'), ('Acre', 'Acre'), ('Hectare', 'Hectare'), ('Bigha', 'Bigha'), ('Biswa', 'Biswa')], max_length=55, null=True)),
                ('bedroom', models.CharField(blank=True, choices=[('1RK', '1RK'), ('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK'), ('5BHK', '5BHK'), ('6BHK', '6BHK'), ('7BHK', '7BHK'), ('8BHK', '8BHK'), ('9BHK', '9BHK'), ('10BHK', '10BHK'), ('11BHK', '11BHK'), ('12BHK', '12BHK'), ('13BHK', '13BHK'), ('14BHK', '14BHK'), ('15BHK', '15BHK'), ('16BHK', '16BHK'), ('17BHK', '17BHK'), ('1BHK', '18BHK'), ('19BHK', '19BHK'), ('20BHK', '20BHK'), ('21BHK', '21BHK'), ('22BHK', '22BHK'), ('23BHK', '23BHK'), ('24BHK', '24BHK'), ('25BHK', '25BHK')], max_length=55, null=True)),
                ('bathroom', models.CharField(blank=True, choices=[('1 Bathroom', '1 Bathroom'), ('2 Bathroom', '2 Bathroom'), ('3 Bathroom', '3 Bathroom'), ('4 Bathroom', '4 Bathroom'), ('5 Bathroom', '5 Bathroom'), ('6 Bathroom', '6 Bathroom'), ('7 Bathroom', '7 Bathroom'), ('8 Bathroom', '8 Bathroom'), ('9 Bathroom', '9 Bathroom'), ('10 Bathroom', '10 Bathroom')], max_length=55, null=True)),
                ('bolconis', models.CharField(blank=True, choices=[('1 Bolconis', '1 Bolconis'), ('2 Bolconis', '2 Bolconis'), ('3 Bolconis', '3 Bolconis'), ('4 Bolconis', '4 Bolconis'), ('5 Bolconis', '5 Bolconis'), ('6 Bolconis', '6 Bolconis'), ('7 Bolconis', '7 Bolconis'), ('8 Bolconis', '8 Bolconis'), ('9 Bolconis', '9 Bolconis'), ('10 Bolconis', '10 Bolconis')], max_length=55, null=True)),
                ('furnishing', models.CharField(blank=True, choices=[('Fully Furnished', 'Fully Furnished'), ('Semi Furnished', 'Semi Furnished'), ('Unfurnished', 'Unfurnished'), ('Ready To Furnished', 'Ready To Furnished'), ('Partially Furnished', 'Partially Furnished')], max_length=55, null=True)),
                ('parking', models.CharField(blank=True, choices=[('1 Parking', '1 Parking'), ('2 Parking', '2 Parking'), ('3 Parking', '3 Parking'), ('4 Parking', '4 Parking'), ('5 Parking', '5 Parking'), ('6 Parking', '6 Parking'), ('7 Parking', '7 Parking'), ('8 Parking', '8 Parking'), ('9 Parking', '9 Parking'), ('10 Parking', '10 Parking'), ('11 Parking', '11 Parking'), ('12 Parking', '12 Parking'), ('13 Parking', '13 Parking'), ('14 Parking', '14 Parking'), ('15 Parking', '15 Parking')], max_length=55, null=True)),
                ('Ownership', models.CharField(blank=True, choices=[('Free Hold', 'Free Hold'), ('Lease Hold', 'Lease Hold'), ('Co-Operative Society', 'Co-Operative Society'), ('Power of Attorney', 'Power of Attorney')], max_length=55, null=True)),
                ('total_floor', models.CharField(blank=True, choices=[('1 ', '1'), ('2 ', '2'), ('3 ', '3'), ('4 ', '4'), ('5 ', '5'), ('6 ', '6'), ('7 ', '7'), ('8 ', '8'), ('9 ', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50')], max_length=55, null=True)),
                ('floor_No', models.CharField(blank=True, choices=[('1 ', '1'), ('2 ', '2'), ('3 ', '3'), ('4 ', '4'), ('5 ', '5'), ('6 ', '6'), ('7 ', '7'), ('8 ', '8'), ('9 ', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50')], max_length=55, null=True)),
                ('description', models.TextField(blank=True, max_length=15000, null=True)),
                ('amenities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Air Condition', 'Air Condition'), ('Badminton Court', 'Badminton Court'), ('balcony', 'balcony'), ('Barbeque', 'Barbeque'), ('Basket Ball', 'Basket Ball'), ('Car Parking', 'Car Parking'), ('CCTV', 'CCTV'), ('club house', 'club house'), ('Community hall', 'Community hall'), ('Conference room', 'Conference room'), ('Creche Area', 'Creche Area'), ('Cricket Pitch', 'Cricket Pitch'), ('Curtains', 'Curtains'), ('Dining Table', 'Dining Table'), ('Electric Vehicle Charging Socket', 'Electric Vehicle Charging Socket'), ('Electrical Switchboard', 'Electrical Switchboard'), ('Elevator', 'Elevator'), ('Exhaust Fan', 'Exhaust Fan'), ('Fans', 'Fans'), ('Fire Fighting Equipment', 'Fire Fighting Equipment'), ('Garden', 'Garden'), ('Geysers', 'Geysers'), ('Grand lobby', 'Grand lobby'), ('Gymnasium', 'Gymnasium'), ('Hammock', 'Hammock'), ('Indoor Games', 'Indoor Games'), ('Intercom', 'Intercom'), ('jacuzzi', 'jacuzzi'), ('Jogging track', 'Jogging track'), ('Kids Play Area', 'Kids Play Area'), ('Library', 'Library'), ('Lights', 'Lights'), ('Live chess', 'Live chess'), ('Microwave', 'Microwave'), ('mini theater', 'mini theater'), ('Modular Kitchen', 'Modular Kitchen'), ('Multipurpose Hall', 'Multipurpose Hall'), ('Rain Water Harvesting', 'Rain Water Harvesting'), ('Reflexology Path', 'Reflexology Path'), ('Refrigerator', 'Refrigerator'), ('Regular Water Supply', 'Regular Water Supply'), ('Rooftop garden', 'Rooftop garden'), ('sauna bath', 'sauna bath'), ('Security', 'Security'), ('Senior citizen area', 'Senior citizen area'), ('Society Office', 'Society Office'), ('Sofa', 'Sofa'), ('Solar Power', 'Solar Power'), ('Spa', 'Spa'), ('Squash court', 'Squash court'), ('Stainless Steel Sink', 'Stainless Steel Sink'), ('Stove', 'Stove'), ('Swimming Pool', 'Swimming Pool'), ('Terrace', 'Terrace'), ('Video Door phone', 'Video Door phone'), ('Volleyball Court', 'Volleyball Court'), ('Wardrobe T.V', 'Wardrobe T.V'), ('Washing Machine', 'Washing Machine'), ('Water Purifier', 'Water Purifier'), ('Water Softener', 'Water Softener'), ('Wi fi', 'Wi fi'), ('yoga deck', 'yoga deck')], max_length=50, null=True)),
                ('other_room', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Home Office', 'Home Office'), ('Library', 'Library'), ('Playroom', 'Playroom'), ('Home Theater', 'Home Theater'), ('Gym Room', 'Gym Room'), ('Game Room', 'Game Room'), ('Wine Cellar', 'Wine Cellar'), ('Home Bar', 'Home Bar'), ('Music Room', 'Music Room'), ('Meditation Room', 'Meditation Room'), ('Sauna Room', 'Sauna Room'), ('Sunroom/Conserv', 'Sunroom/Conserv')], max_length=50, null=True)),
                ('project_size', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('featured_property', models.BooleanField(default=False)),
                ('youtube_link', models.CharField(blank=True, max_length=250, null=True)),
                ('house_flat_no', models.CharField(blank=True, max_length=50, null=True)),
                ('building_name', models.CharField(blank=True, max_length=150, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('landmark', models.CharField(blank=True, max_length=150, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=55, null=True)),
                ('slug', models.SlugField(blank=True, max_length=555, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.city')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.locality')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='residential.resell')),
            ],
            options={
                'verbose_name_plural': '1. ReSell Property',
            },
        ),
        migrations.CreateModel(
            name='Furnished_Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wardrobe', models.CharField(blank=True, max_length=25, null=True)),
                ('Fan', models.CharField(blank=True, max_length=25, null=True)),
                ('Exhaust_Fan', models.CharField(blank=True, max_length=25, null=True)),
                ('Geyser', models.CharField(blank=True, max_length=25, null=True)),
                ('Modular_Kitchen', models.CharField(blank=True, max_length=25, null=True)),
                ('Light', models.CharField(blank=True, max_length=25, null=True)),
                ('AC', models.CharField(blank=True, max_length=25, null=True)),
                ('Curtains', models.CharField(blank=True, max_length=25, null=True)),
                ('Bed', models.CharField(blank=True, max_length=25, null=True)),
                ('Chimney', models.CharField(blank=True, max_length=25, null=True)),
                ('Dining_Table', models.CharField(blank=True, max_length=25, null=True)),
                ('Microwave', models.CharField(blank=True, max_length=25, null=True)),
                ('Fridge', models.CharField(blank=True, max_length=25, null=True)),
                ('Sofa', models.CharField(blank=True, max_length=25, null=True)),
                ('Stove', models.CharField(blank=True, max_length=25, null=True)),
                ('TV', models.CharField(blank=True, max_length=25, null=True)),
                ('Washing_Machine', models.CharField(blank=True, max_length=25, null=True)),
                ('Water_Purifier', models.CharField(blank=True, max_length=25, null=True)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.resell')),
            ],
            options={
                'verbose_name_plural': '6. Furnished_Amenities',
            },
        ),
        migrations.CreateModel(
            name='ReSell_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('rate', models.IntegerField(default=1)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='New', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.resell')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '2. ReSell Comment',
            },
        ),
        migrations.CreateModel(
            name='ReSell_Floor_Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_room', models.CharField(blank=True, choices=[('1RK', '1RK'), ('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK'), ('5BHK', '5BHK'), ('6BHK', '6BHK'), ('7BHK', '7BHK'), ('8BHK', '8BHK'), ('9BHK', '9BHK'), ('10BHK', '10BHK'), ('11BHK', '11BHK'), ('12BHK', '12BHK'), ('13BHK', '13BHK'), ('14BHK', '14BHK'), ('15BHK', '15BHK'), ('16BHK', '16BHK'), ('17BHK', '17BHK'), ('1BHK', '18BHK'), ('19BHK', '19BHK'), ('20BHK', '20BHK'), ('21BHK', '21BHK'), ('22BHK', '22BHK'), ('23BHK', '23BHK'), ('24BHK', '24BHK'), ('25BHK', '25BHK')], max_length=25, null=True)),
                ('carpet_area', models.CharField(blank=True, max_length=50, null=True)),
                ('arey_type', models.CharField(blank=True, choices=[('Square Feet', 'Square Feet'), ('Square Meter', 'Square Meter'), ('Square Yard', 'Square Yard'), ('Acre', 'Acre'), ('Hectare', 'Hectare'), ('Bigha', 'Bigha'), ('Biswa', 'Biswa')], max_length=25, null=True)),
                ('bath_room', models.CharField(blank=True, choices=[('1 Bathroom', '1 Bathroom'), ('2 Bathroom', '2 Bathroom'), ('3 Bathroom', '3 Bathroom'), ('4 Bathroom', '4 Bathroom'), ('5 Bathroom', '5 Bathroom'), ('6 Bathroom', '6 Bathroom'), ('7 Bathroom', '7 Bathroom'), ('8 Bathroom', '8 Bathroom'), ('9 Bathroom', '9 Bathroom'), ('10 Bathroom', '10 Bathroom')], max_length=25, null=True)),
                ('bolconis', models.CharField(blank=True, choices=[('1 Bolconis', '1 Bolconis'), ('2 Bolconis', '2 Bolconis'), ('3 Bolconis', '3 Bolconis'), ('4 Bolconis', '4 Bolconis'), ('5 Bolconis', '5 Bolconis'), ('6 Bolconis', '6 Bolconis'), ('7 Bolconis', '7 Bolconis'), ('8 Bolconis', '8 Bolconis'), ('9 Bolconis', '9 Bolconis'), ('10 Bolconis', '10 Bolconis')], max_length=25, null=True)),
                ('price', models.CharField(blank=True, max_length=25, null=True)),
                ('floor_plan', models.ImageField(upload_to='images/')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.resell')),
            ],
            options={
                'verbose_name_plural': '5. Residential Project Flor Plan',
            },
        ),
        migrations.CreateModel(
            name='ReSell_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.resell')),
            ],
            options={
                'verbose_name_plural': '3. Sell Images',
            },
        ),
    ]
