# Generated by Django 5.0.2 on 2025-04-19 08:33

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resell',
            name='Ownership',
            field=models.CharField(blank=True, choices=[('Free Hold', 'Free Hold'), ('Lease Hold', 'Lease Hold'), ('Co-Operative Society', 'Co-Operative Society'), ('Power of Attorney', 'Power of Attorney')], max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='age_of_properties',
            field=models.CharField(blank=True, choices=[(' under construction', ' under construction'), ('0 To 5 Years', '0 To 5 Years'), ('5 TO 10 Years', '5 TO 10 Years'), ('10 To 15 Years', '10 To 15 Years'), ('15 To 20 Years', '15 To 20 Years'), ('20 To 25 Years', '20 To 25 Years')], max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='area_type',
            field=models.CharField(blank=True, choices=[('Square Feet', 'Square Feet'), ('Square Meter', 'Square Meter'), ('Square Yard', 'Square Yard'), ('Acre', 'Acre'), ('Hectare', 'Hectare'), ('Bigha', 'Bigha'), ('Biswa', 'Biswa')], max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='bathroom',
            field=models.CharField(blank=True, choices=[('1 Bathroom', '1 Bathroom'), ('2 Bathroom', '2 Bathroom'), ('3 Bathroom', '3 Bathroom'), ('4 Bathroom', '4 Bathroom'), ('5 Bathroom', '5 Bathroom'), ('6 Bathroom', '6 Bathroom'), ('7 Bathroom', '7 Bathroom'), ('8 Bathroom', '8 Bathroom'), ('9 Bathroom', '9 Bathroom'), ('10 Bathroom', '10 Bathroom')], max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='bedroom',
            field=models.CharField(blank=True, choices=[('1RK', '1RK'), ('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK'), ('5BHK', '5BHK'), ('6BHK', '6BHK'), ('7BHK', '7BHK'), ('8BHK', '8BHK'), ('9BHK', '9BHK'), ('10BHK', '10BHK'), ('11BHK', '11BHK'), ('12BHK', '12BHK'), ('13BHK', '13BHK'), ('14BHK', '14BHK'), ('15BHK', '15BHK'), ('16BHK', '16BHK'), ('17BHK', '17BHK'), ('1BHK', '18BHK'), ('19BHK', '19BHK'), ('20BHK', '20BHK'), ('21BHK', '21BHK'), ('22BHK', '22BHK'), ('23BHK', '23BHK'), ('24BHK', '24BHK'), ('25BHK', '25BHK')], max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='bolconis',
            field=models.CharField(blank=True, choices=[('1 Bolconis', '1 Bolconis'), ('2 Bolconis', '2 Bolconis'), ('3 Bolconis', '3 Bolconis'), ('4 Bolconis', '4 Bolconis'), ('5 Bolconis', '5 Bolconis'), ('6 Bolconis', '6 Bolconis'), ('7 Bolconis', '7 Bolconis'), ('8 Bolconis', '8 Bolconis'), ('9 Bolconis', '9 Bolconis'), ('10 Bolconis', '10 Bolconis')], max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='building_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='floor_No',
            field=models.CharField(blank=True, choices=[('1 ', '1'), ('2 ', '2'), ('3 ', '3'), ('4 ', '4'), ('5 ', '5'), ('6 ', '6'), ('7 ', '7'), ('8 ', '8'), ('9 ', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50')], max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('Fully Furnished', 'Fully Furnished'), ('Semi Furnished', 'Semi Furnished'), ('Unfurnished', 'Unfurnished'), ('Ready To Furnished', 'Ready To Furnished'), ('Partially Furnished', 'Partially Furnished')], max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='house_flat_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='landmark',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='other_room',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Home Office', 'Home Office'), ('Library', 'Library'), ('Playroom', 'Playroom'), ('Home Theater', 'Home Theater'), ('Gym Room', 'Gym Room'), ('Game Room', 'Game Room'), ('Wine Cellar', 'Wine Cellar'), ('Home Bar', 'Home Bar'), ('Music Room', 'Music Room'), ('Meditation Room', 'Meditation Room'), ('Sauna Room', 'Sauna Room'), ('Sunroom/Conserv', 'Sunroom/Conserv')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='parking',
            field=models.CharField(blank=True, choices=[('1 Parking', '1 Parking'), ('2 Parking', '2 Parking'), ('3 Parking', '3 Parking'), ('4 Parking', '4 Parking'), ('5 Parking', '5 Parking'), ('6 Parking', '6 Parking'), ('7 Parking', '7 Parking'), ('8 Parking', '8 Parking'), ('9 Parking', '9 Parking'), ('10 Parking', '10 Parking'), ('11 Parking', '11 Parking'), ('12 Parking', '12 Parking'), ('13 Parking', '13 Parking'), ('14 Parking', '14 Parking'), ('15 Parking', '15 Parking')], max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='pin_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='total_floor',
            field=models.CharField(blank=True, choices=[('1 ', '1'), ('2 ', '2'), ('3 ', '3'), ('4 ', '4'), ('5 ', '5'), ('6 ', '6'), ('7 ', '7'), ('8 ', '8'), ('9 ', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50')], max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resell',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
