# Generated by Django 5.0.2 on 2025-04-19 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0002_resell_ownership_resell_age_of_properties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furnished_Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wardrobe', models.CharField(blank=True, max_length=25, null=True)),
                ('Fan', models.CharField(blank=True, max_length=25, null=True)),
                ('Exhaust_Fan', models.CharField(blank=True, max_length=25, null=True)),
                ('Geyser', models.CharField(blank=True, max_length=25, null=True)),
                ('Modular_Kitchen', models.CharField(blank=True, max_length=25, null=True)),
                ('Light', models.CharField(blank=True, max_length=25, null=True)),
                ('AC', models.CharField(blank=True, max_length=25, null=True)),
                ('Curtains', models.CharField(blank=True, max_length=25, null=True)),
                ('Bed', models.CharField(blank=True, max_length=25, null=True)),
                ('Chimney', models.CharField(blank=True, max_length=25, null=True)),
                ('Dining_Table', models.CharField(blank=True, max_length=25, null=True)),
                ('Microwave', models.CharField(blank=True, max_length=25, null=True)),
                ('Fridge', models.CharField(blank=True, max_length=25, null=True)),
                ('Sofa', models.CharField(blank=True, max_length=25, null=True)),
                ('Stove', models.CharField(blank=True, max_length=25, null=True)),
                ('TV', models.CharField(blank=True, max_length=25, null=True)),
                ('Washing_Machine', models.CharField(blank=True, max_length=25, null=True)),
                ('Water_Purifier', models.CharField(blank=True, max_length=25, null=True)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.resell')),
            ],
            options={
                'verbose_name_plural': '6. Furnished_Amenities',
            },
        ),
        migrations.CreateModel(
            name='ReSell_Floor_Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_room', models.CharField(blank=True, choices=[('1RK', '1RK'), ('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK'), ('5BHK', '5BHK'), ('6BHK', '6BHK'), ('7BHK', '7BHK'), ('8BHK', '8BHK'), ('9BHK', '9BHK'), ('10BHK', '10BHK'), ('11BHK', '11BHK'), ('12BHK', '12BHK'), ('13BHK', '13BHK'), ('14BHK', '14BHK'), ('15BHK', '15BHK'), ('16BHK', '16BHK'), ('17BHK', '17BHK'), ('1BHK', '18BHK'), ('19BHK', '19BHK'), ('20BHK', '20BHK'), ('21BHK', '21BHK'), ('22BHK', '22BHK'), ('23BHK', '23BHK'), ('24BHK', '24BHK'), ('25BHK', '25BHK')], max_length=25, null=True)),
                ('carpet_area', models.CharField(blank=True, max_length=50, null=True)),
                ('arey_type', models.CharField(blank=True, choices=[('Square Feet', 'Square Feet'), ('Square Meter', 'Square Meter'), ('Square Yard', 'Square Yard'), ('Acre', 'Acre'), ('Hectare', 'Hectare'), ('Bigha', 'Bigha'), ('Biswa', 'Biswa')], max_length=25, null=True)),
                ('bath_room', models.CharField(blank=True, choices=[('1 Bathroom', '1 Bathroom'), ('2 Bathroom', '2 Bathroom'), ('3 Bathroom', '3 Bathroom'), ('4 Bathroom', '4 Bathroom'), ('5 Bathroom', '5 Bathroom'), ('6 Bathroom', '6 Bathroom'), ('7 Bathroom', '7 Bathroom'), ('8 Bathroom', '8 Bathroom'), ('9 Bathroom', '9 Bathroom'), ('10 Bathroom', '10 Bathroom')], max_length=25, null=True)),
                ('bolconis', models.CharField(blank=True, choices=[('1 Bolconis', '1 Bolconis'), ('2 Bolconis', '2 Bolconis'), ('3 Bolconis', '3 Bolconis'), ('4 Bolconis', '4 Bolconis'), ('5 Bolconis', '5 Bolconis'), ('6 Bolconis', '6 Bolconis'), ('7 Bolconis', '7 Bolconis'), ('8 Bolconis', '8 Bolconis'), ('9 Bolconis', '9 Bolconis'), ('10 Bolconis', '10 Bolconis')], max_length=25, null=True)),
                ('price', models.CharField(blank=True, max_length=25, null=True)),
                ('floor_plan', models.ImageField(upload_to='images/')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.resell')),
            ],
            options={
                'verbose_name_plural': '5. Residential Project Flor Plan',
            },
        ),
    ]
