# Generated by Django 5.0.2 on 2025-07-06 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0003_furnished_amenities_resell_floor_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resell',
            name='city',
        ),
        migrations.RemoveField(
            model_name='resell',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='resell',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='resell_comment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='resell_images',
            name='project',
        ),
        migrations.RemoveField(
            model_name='resell_floor_plans',
            name='Project',
        ),
        migrations.RemoveField(
            model_name='resell_comment',
            name='user',
        ),
        migrations.CreateModel(
            name='SellProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('independent_house', 'Independent House'), ('villa', 'Villa'), ('plot', 'Plot/Land'), ('commercial', 'Commercial Property')], max_length=30)),
                ('bhk', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='BHK (Bedrooms)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('area_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('furnishing', models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi Furnished'), ('fully_furnished', 'Fully Furnished')], default='unfurnished', max_length=30)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('pending', 'Pending')], default='available', max_length=20)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('image_main', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='residential.sellproperty')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('contacted_on', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='residential.sellproperty')),
            ],
        ),
        migrations.DeleteModel(
            name='Furnished_Amenities',
        ),
        migrations.DeleteModel(
            name='ReSell_Images',
        ),
        migrations.DeleteModel(
            name='ReSell',
        ),
        migrations.DeleteModel(
            name='ReSell_Floor_Plans',
        ),
        migrations.DeleteModel(
            name='ReSell_Comment',
        ),
    ]
