# Generated by Django 5.0.1 on 2024-01-21 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_our_team_social_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social_site',
            old_name='color_code',
            new_name='icone_code',
        ),
        migrations.RenameField(
            model_name='social_site',
            old_name='title',
            new_name='site',
        ),
        migrations.RemoveField(
            model_name='social_site',
            name='Social_link',
        ),
        migrations.CreateModel(
            name='Social_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('our_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.our_team')),
                ('social_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.social_site')),
            ],
        ),
    ]
