# Generated by Django 5.0.1 on 2024-01-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_color_code_social_site_icone_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_team',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='our_team',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='header_footer_color',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='setting',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='text_color',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
