# Generated by Django 5.0.1 on 2024-01-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_about_page_contact_page_delete_header_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_page',
            old_name='contctus',
            new_name='aboutus',
        ),
        migrations.RenameField(
            model_name='contact_page',
            old_name='aboutus',
            new_name='contctus',
        ),
        migrations.AddField(
            model_name='about_page',
            name='mission',
            field=models.CharField(blank=True, max_length=2055),
        ),
        migrations.AddField(
            model_name='about_page',
            name='values',
            field=models.CharField(blank=True, max_length=2055),
        ),
        migrations.AddField(
            model_name='about_page',
            name='vision',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='setting',
            name='copy_right',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='google_map',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
