# Generated by Django 5.0.1 on 2024-01-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_contctus_about_page_aboutus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='fax',
            new_name='whatsapp',
        ),
    ]
