# Generated by Django 5.0.1 on 2024-01-27 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_testimonial'),
        ('utility', '0008_social_site_alter_age_of_properties_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_link',
            name='social_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.social_site'),
        ),
        migrations.AlterModelOptions(
            name='about_page',
            options={'verbose_name_plural': '2. About Page'},
        ),
        migrations.AlterModelOptions(
            name='contact_page',
            options={'verbose_name_plural': '3. Contact Page'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name_plural': '1. ContactMessage'},
        ),
        migrations.AlterModelOptions(
            name='our_team',
            options={'verbose_name_plural': '4. Our Team'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name_plural': '9. Web Site Setting'},
        ),
        migrations.AlterModelOptions(
            name='social_link',
            options={'verbose_name_plural': '6. Social Link'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name_plural': '5. Testimonial'},
        ),
        migrations.DeleteModel(
            name='Social_Site',
        ),
    ]
