# Generated by Django 5.0.2 on 2025-07-19 16:43

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0010_delete_ownerprofile'),
        ('utility', '0014_delete_possession_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('construction_status', models.CharField(choices=[('Under Construction', 'Under Construction'), ('Ready To Move', 'Ready To Move'), ('New Launch', 'New Launch')], max_length=30)),
                ('property_type', models.CharField(choices=[('Commercial Office Space', 'Commercial Office Space'), ('Shops', 'Shops'), ('Showroom', 'Showroom'), ('Commercial Plot', 'Commercial Plot'), ('Co-working Space', 'Co-working Space'), ('Warehouse/Godown', 'Warehouse/Godown')], max_length=200)),
                ('total_floors', models.CharField(blank=True, max_length=10, null=True)),
                ('possession_year', models.CharField(blank=True, choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039')], max_length=200, null=True)),
                ('priceing', models.CharField(blank=True, max_length=50, null=True)),
                ('area_range', models.CharField(blank=True, max_length=50, null=True)),
                ('featured_property', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/commercial/')),
                ('slug', models.SlugField(blank=True, max_length=555, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.city')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.developer')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.locality')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project.commercialproject')),
            ],
            options={
                'verbose_name_plural': '2. Commercial Projects',
            },
        ),
        migrations.CreateModel(
            name='CommercialOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviews', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_map_iframe', models.TextField(blank=True, null=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('keywords', models.CharField(blank=True, max_length=2000, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/commercial/')),
                ('welcome_to_bg', models.ImageField(blank=True, null=True, upload_to='headers/commercial/')),
                ('virtual_site_visit_bg', models.ImageField(blank=True, null=True, upload_to='headers/commercial/')),
                ('schedule_a_site_visit', models.ImageField(blank=True, null=True, upload_to='headers/commercial/')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/commercial/')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('contacted_on', models.DateTimeField(auto_now_add=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='project.commercialproject')),
            ],
            options={
                'verbose_name_plural': '4. Commercial Enquiry',
            },
        ),
        migrations.CreateModel(
            name='CommercialConnectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectivity', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialBookingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_offers', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialBankOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bank_approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_booking_offers', to='utility.bank')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_offers', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutus', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialProjectAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_amenities', to='utility.p_amenities')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialRERAInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='overviewimage/commercial/')),
                ('registration_no', models.CharField(blank=True, max_length=50, null=True)),
                ('project_registered', models.CharField(blank=True, max_length=50, null=True)),
                ('government_rera_authorised_advertiser', models.CharField(blank=True, max_length=150, null=True)),
                ('site_address', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_us', models.CharField(blank=True, max_length=500, null=True)),
                ('disclaimer', models.CharField(blank=True, max_length=1500, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='rera_docs/commercial/')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rera', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialUSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(blank=True, max_length=150, null=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usps', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialWebSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='web_slider/commercial/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialWelcomeTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=5500, null=True)),
                ('read_more', models.TextField(blank=True, max_length=5500, null=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcomes', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialWhyInvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_invest', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='Residential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Occupancy_Certificate', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True)),
                ('Commencement_Certificate', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True)),
                ('construction_status', models.CharField(choices=[('Under Construction', 'Under Construction'), ('New Launch', 'New Launch'), ('Partially Ready To Move', 'Partially Ready To Move'), ('Ready To Move', 'Ready To Move'), ('Deleverd', 'Deleverd')], max_length=25)),
                ('propert_type', models.CharField(choices=[('1 RK Studio Apartment', '1 RK Studio Apartment'), ('Agricultural Farm Land', 'Agricultural Farm Land'), ('Farm House', 'Farm House'), ('Independent Builder Floor', 'Independent House Villa'), ('Residential Apartment', 'Residential Apartment')], max_length=200)),
                ('project_name', models.CharField(max_length=250)),
                ('land_parce', models.CharField(blank=True, max_length=50, null=True)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('possession', models.CharField(blank=True, max_length=50, null=True)),
                ('possession_year', models.CharField(blank=True, choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039')], max_length=200, null=True)),
                ('luxurious', models.CharField(blank=True, max_length=50, null=True)),
                ('priceing', models.CharField(blank=True, max_length=50, null=True)),
                ('featured_property', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slug', models.SlugField(blank=True, max_length=555, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.city')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.developer')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.locality')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project.residential')),
            ],
            options={
                'verbose_name_plural': '1. Residential Project',
            },
        ),
        migrations.CreateModel(
            name='RERA_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='overviewimage/')),
                ('registration_no', models.CharField(blank=True, max_length=50, null=True)),
                ('project_registered', models.CharField(blank=True, max_length=50, null=True)),
                ('government_rera_authorised_advertiser', models.CharField(blank=True, max_length=150, null=True)),
                ('site_address', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_us', models.CharField(blank=True, max_length=500, null=True)),
                ('disclaimer', models.CharField(blank=True, max_length=1500, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='rera_docs/')),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rera', to='project.residential')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='utility.p_amenities')),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='project.residential')),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviews', to='project.residential')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_map_iframe', models.TextField(blank=True, null=True)),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='project.residential')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('keywords', models.CharField(blank=True, max_length=2000, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('welcome_to_bg', models.ImageField(blank=True, null=True, upload_to='headers/')),
                ('virtual_site_visit_bg', models.ImageField(blank=True, null=True, upload_to='headers/')),
                ('schedule_a_site_visit', models.ImageField(blank=True, null=True, upload_to='headers/')),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='project.residential')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='project.residential')),
            ],
        ),
        migrations.CreateModel(
            name='Connectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='project.residential')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhk_type', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='project.residential')),
            ],
        ),
        migrations.CreateModel(
            name='BookingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BookingOffer', to='project.residential')),
            ],
        ),
        migrations.CreateModel(
            name='BankOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bank_approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_offers', to='utility.bank')),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_offers', to='project.residential')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutus', to='project.residential')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('contacted_on', models.DateTimeField(auto_now_add=True)),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='project.residential')),
            ],
            options={
                'verbose_name_plural': '3. Residential Enquiry',
            },
        ),
        migrations.CreateModel(
            name='USP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(blank=True, max_length=150, null=True)),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usps', to='project.residential')),
            ],
        ),
        migrations.CreateModel(
            name='WebSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='web_slider/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='project.residential')),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=5500, null=True)),
                ('read_more', models.TextField(blank=True, max_length=5500, null=True)),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcomes', to='project.residential')),
            ],
        ),
        migrations.CreateModel(
            name='WhyInvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350, null=True)),
                ('discripation', models.CharField(blank=True, max_length=500, null=True)),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_invest', to='project.residential')),
            ],
        ),
    ]
