# Generated by Django 5.0.2 on 2025-04-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_commercial_project_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residential_project',
            name='max_price',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='residential_project',
            name='min_price',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='residential_project',
            name='total_tower',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='residential_project',
            name='totle_unit',
            field=models.CharField(max_length=5),
        ),
    ]
