# Generated by Django 5.0.1 on 2024-01-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_commercial_project_floor_plans_floor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercial_project_floor_plans',
            options={'verbose_name_plural': '7. Commercial Project Floor Plan'},
        ),
        migrations.AlterModelOptions(
            name='commercial_project_images',
            options={'verbose_name_plural': '8. Commercial Project Images'},
        ),
        migrations.AlterModelOptions(
            name='residential_project_floor_plans',
            options={'verbose_name_plural': '6. Residential Project Flor Plan'},
        ),
        migrations.AlterModelOptions(
            name='residential_project_images',
            options={'verbose_name_plural': '5. Residential Project Images'},
        ),
    ]
