# Generated by Django 5.0.2 on 2025-04-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_residential_project_max_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial_project',
            name='description',
            field=models.TextField(blank=True, max_length=15000, null=True),
        ),
        migrations.AlterField(
            model_name='residential_project',
            name='description',
            field=models.TextField(blank=True, max_length=15000, null=True),
        ),
        migrations.AlterField(
            model_name='residential_project',
            name='slug',
            field=models.SlugField(blank=True, max_length=555, null=True, unique=True),
        ),
    ]
