# Generated by Django 5.0.2 on 2025-04-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_commercial_project_possession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercial_project_floor_plans',
            name='floor',
        ),
        migrations.AlterField(
            model_name='commercial_project_floor_plans',
            name='arey_type',
            field=models.CharField(blank=True, choices=[('Square Feet', 'Square Feet'), ('Square Meter', 'Square Meter'), ('Square Yard', 'Square Yard'), ('Acre', 'Acre'), ('Hectare', 'Hectare'), ('Bigha', 'Bigha'), ('Biswa', 'Biswa')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='commercial_project_floor_plans',
            name='bath_room',
            field=models.CharField(blank=True, choices=[('1 Bathroom', '1 Bathroom'), ('2 Bathroom', '2 Bathroom'), ('3 Bathroom', '3 Bathroom'), ('4 Bathroom', '4 Bathroom'), ('5 Bathroom', '5 Bathroom'), ('6 Bathroom', '6 Bathroom'), ('7 Bathroom', '7 Bathroom'), ('8 Bathroom', '8 Bathroom'), ('9 Bathroom', '9 Bathroom'), ('10 Bathroom', '10 Bathroom')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='commercial_project_floor_plans',
            name='bolconis',
            field=models.CharField(blank=True, choices=[('1 Bolconis', '1 Bolconis'), ('2 Bolconis', '2 Bolconis'), ('3 Bolconis', '3 Bolconis'), ('4 Bolconis', '4 Bolconis'), ('5 Bolconis', '5 Bolconis'), ('6 Bolconis', '6 Bolconis'), ('7 Bolconis', '7 Bolconis'), ('8 Bolconis', '8 Bolconis'), ('9 Bolconis', '9 Bolconis'), ('10 Bolconis', '10 Bolconis')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='residential_project_floor_plans',
            name='arey_type',
            field=models.CharField(blank=True, choices=[('Square Feet', 'Square Feet'), ('Square Meter', 'Square Meter'), ('Square Yard', 'Square Yard'), ('Acre', 'Acre'), ('Hectare', 'Hectare'), ('Bigha', 'Bigha'), ('Biswa', 'Biswa')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='residential_project_floor_plans',
            name='bath_room',
            field=models.CharField(blank=True, choices=[('1 Bathroom', '1 Bathroom'), ('2 Bathroom', '2 Bathroom'), ('3 Bathroom', '3 Bathroom'), ('4 Bathroom', '4 Bathroom'), ('5 Bathroom', '5 Bathroom'), ('6 Bathroom', '6 Bathroom'), ('7 Bathroom', '7 Bathroom'), ('8 Bathroom', '8 Bathroom'), ('9 Bathroom', '9 Bathroom'), ('10 Bathroom', '10 Bathroom')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='residential_project_floor_plans',
            name='bed_room',
            field=models.CharField(blank=True, choices=[('1RK', '1RK'), ('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK'), ('5BHK', '5BHK'), ('6BHK', '6BHK'), ('7BHK', '7BHK'), ('8BHK', '8BHK'), ('9BHK', '9BHK'), ('10BHK', '10BHK'), ('11BHK', '11BHK'), ('12BHK', '12BHK'), ('13BHK', '13BHK'), ('14BHK', '14BHK'), ('15BHK', '15BHK'), ('16BHK', '16BHK'), ('17BHK', '17BHK'), ('1BHK', '18BHK'), ('19BHK', '19BHK'), ('20BHK', '20BHK'), ('21BHK', '21BHK'), ('22BHK', '22BHK'), ('23BHK', '23BHK'), ('24BHK', '24BHK'), ('25BHK', '25BHK')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='residential_project_floor_plans',
            name='bolconis',
            field=models.CharField(blank=True, choices=[('1 Bolconis', '1 Bolconis'), ('2 Bolconis', '2 Bolconis'), ('3 Bolconis', '3 Bolconis'), ('4 Bolconis', '4 Bolconis'), ('5 Bolconis', '5 Bolconis'), ('6 Bolconis', '6 Bolconis'), ('7 Bolconis', '7 Bolconis'), ('8 Bolconis', '8 Bolconis'), ('9 Bolconis', '9 Bolconis'), ('10 Bolconis', '10 Bolconis')], max_length=25, null=True),
        ),
    ]
