# Generated by Django 5.0.2 on 2025-04-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_commercial_project_floor_plans_floor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercial_project',
            name='slider',
        ),
        migrations.RemoveField(
            model_name='residential_project',
            name='slider',
        ),
    ]
