# Generated by Django 5.0.2 on 2025-04-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_commercial_project_slider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial_project_floor_plans',
            name='price',
            field=models.CharField(blank=True, default=0, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='residential_project_floor_plans',
            name='price',
            field=models.CharField(blank=True, default=0, max_length=25, null=True),
        ),
    ]
