# Generated by Django 5.0.2 on 2025-04-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_commercial_project_floor_plans_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residential_project_floor_plans',
            name='price',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
