# Generated by Django 5.0.2 on 2025-04-18 19:19

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_residential_project_other_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residential_project',
            name='other_room',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Home Office', 'Home Office'), ('Library', 'Library'), ('Playroom', 'Playroom'), ('Home Theater', 'Home Theater'), ('Gym Room', 'Gym Room'), ('Game Room', 'Game Room'), ('Wine Cellar', 'Wine Cellar'), ('Home Bar', 'Home Bar'), ('Music Room', 'Music Room'), ('Meditation Room', 'Meditation Room'), ('Sauna Room', 'Sauna Room'), ('Sunroom/Conserv', 'Sunroom/Conserv')], max_length=50, null=True),
        ),
    ]
