# Generated by Django 5.0.2 on 2025-06-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_amenities_remove_commercial_project_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residential',
            old_name='logo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='residential',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='residential',
            name='price',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
