# Generated by Django 5.0.2 on 2025-06-30 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_rename_logo_residential_image_and_more'),
        ('utility', '0010_p_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_amenities',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='maharera',
            name='residential',
        ),
        migrations.RemoveField(
            model_name='reraadditional',
            name='residential',
        ),
        migrations.RemoveField(
            model_name='header',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='header',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='header',
            name='title',
        ),
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.RemoveField(
            model_name='residential',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='residential',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='welcometo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='whyinvest',
            name='reason',
        ),
        migrations.AddField(
            model_name='header',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='schedule_a_site_visit',
            field=models.ImageField(blank=True, null=True, upload_to='headers/'),
        ),
        migrations.AddField(
            model_name='header',
            name='virtual_site_visit_bg',
            field=models.ImageField(blank=True, null=True, upload_to='headers/'),
        ),
        migrations.AddField(
            model_name='header',
            name='welcome_to_bg',
            field=models.ImageField(blank=True, null=True, upload_to='headers/'),
        ),
        migrations.AddField(
            model_name='project_amenities',
            name='amenities',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='utility.p_amenities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='welcometo',
            name='read_more',
            field=models.TextField(blank=True, max_length=5500, null=True),
        ),
        migrations.AddField(
            model_name='whyinvest',
            name='discripation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='whyinvest',
            name='title',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='residential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='project.residential'),
        ),
        migrations.AlterField(
            model_name='location',
            name='google_map_iframe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residential',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='usp',
            name='point',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='welcometo',
            name='title',
            field=models.CharField(blank=True, max_length=5500, null=True),
        ),
        migrations.CreateModel(
            name='Connectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='project.residential')),
            ],
        ),
        migrations.CreateModel(
            name='RERA_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(upload_to='overviewimage/')),
                ('registration_no', models.CharField(blank=True, max_length=50, null=True)),
                ('project_registered', models.CharField(blank=True, max_length=50, null=True)),
                ('government_rera_authorised_advertiser', models.CharField(blank=True, max_length=150, null=True)),
                ('site_address', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_us', models.CharField(blank=True, max_length=500, null=True)),
                ('disclaimer', models.CharField(blank=True, max_length=1500, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='rera_docs/')),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rera', to='project.residential')),
            ],
        ),
        migrations.DeleteModel(
            name='Amenities',
        ),
        migrations.DeleteModel(
            name='MahaRERA',
        ),
        migrations.DeleteModel(
            name='RERAAdditional',
        ),
    ]
