# Generated by Django 5.0.2 on 2025-06-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_remove_project_amenities_name1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcometo',
            name='title',
        ),
        migrations.AddField(
            model_name='welcometo',
            name='description',
            field=models.TextField(blank=True, max_length=5500, null=True),
        ),
        migrations.AlterField(
            model_name='rera_info',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='overviewimage/'),
        ),
    ]
