# Generated by Django 5.0.2 on 2025-07-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_bookingoffer_bank_approval_bookingoffer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residential',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residential',
            name='featured_property',
            field=models.BooleanField(default=False),
        ),
    ]
