# Generated by Django 5.0.2 on 2025-07-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_residential_active_residential_featured_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residential',
            name='image',
        ),
        migrations.AddField(
            model_name='header',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='header',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='residential',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='residential',
            name='slug',
            field=models.SlugField(blank=True, max_length=555, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='residential',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='keywords',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='meta_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
