# Generated by Django 5.0.2 on 2025-07-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_remove_residential_image_header_logo_header_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residential',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
