# Generated by Django 5.0.2 on 2025-07-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_residential_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residential',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
