# Generated by Django 5.0.2 on 2025-07-03 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_alter_residential_image'),
        ('utility', '0011_remove_locality_featured_locality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingoffer',
            name='bank_approval',
        ),
        migrations.RemoveField(
            model_name='bookingoffer',
            name='description',
        ),
        migrations.AlterField(
            model_name='bookingoffer',
            name='residential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BookingOffer', to='project.residential'),
        ),
        migrations.AlterField(
            model_name='bookingoffer',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='bankOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bank_approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_offers', to='utility.bank')),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_offers', to='project.residential')),
            ],
        ),
    ]
