# Generated by Django 5.0.2 on 2025-07-03 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_remove_bookingoffer_bank_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankoffer',
            name='residential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_offers', to='project.residential'),
        ),
    ]
