# Generated by Django 5.0.2 on 2025-07-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_alter_bankoffer_residential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residential',
            name='land_parceland',
        ),
        migrations.AddField(
            model_name='residential',
            name='land_parce',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='residential',
            name='Possession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='residential',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
