# Generated by Django 5.0.2 on 2025-07-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_remove_residential_land_parceland_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residential',
            old_name='floor',
            new_name='Priceing',
        ),
        migrations.AddField(
            model_name='residential',
            name='luxurious',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
