# Generated by Django 5.0.2 on 2025-07-04 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_rename_floor_residential_priceing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residential',
            old_name='Possession',
            new_name='possession',
        ),
        migrations.RenameField(
            model_name='residential',
            old_name='Priceing',
            new_name='priceing',
        ),
        migrations.RemoveField(
            model_name='residential',
            name='price',
        ),
    ]
