# Generated by Django 5.0.2 on 2025-07-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_rename_possession_residential_possession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residential',
            name='description',
        ),
        migrations.AddField(
            model_name='residential',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
