# Generated by Django 5.0.2 on 2025-07-04 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_remove_residential_description_residential_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='caption',
        ),
    ]
