# Generated by Django 5.0.2 on 2025-07-06 13:06

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_remove_gallery_caption'),
        ('user', '0010_delete_ownerprofile'),
        ('utility', '0012_visit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('construction_status', models.CharField(choices=[('Under Construction', 'Under Construction'), ('Ready To Move', 'Ready To Move'), ('New Launch', 'New Launch')], max_length=30)),
                ('property_type', models.CharField(choices=[('Commercial Office Space', 'Commercial Office Space'), ('Shops', 'Shops'), ('Showroom', 'Showroom'), ('Commercial Plot', 'Commercial Plot'), ('Co-working Space', 'Co-working Space'), ('Warehouse/Godown', 'Warehouse/Godown')], max_length=200)),
                ('total_floors', models.CharField(blank=True, max_length=10, null=True)),
                ('possession_year', models.CharField(blank=True, max_length=4, null=True)),
                ('priceing', models.CharField(blank=True, max_length=50, null=True)),
                ('area_range', models.CharField(blank=True, max_length=50, null=True)),
                ('featured_property', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/commercial/')),
                ('slug', models.SlugField(blank=True, max_length=555, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.city')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.developer')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.locality')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project.commercialproject')),
            ],
            options={
                'verbose_name_plural': '2. Commercial Projects',
            },
        ),
        migrations.CreateModel(
            name='CommercialOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviews', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_map_iframe', models.TextField(blank=True, null=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('keywords', models.CharField(blank=True, max_length=2000, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/commercial/')),
                ('welcome_to_bg', models.ImageField(blank=True, null=True, upload_to='headers/commercial/')),
                ('virtual_site_visit_bg', models.ImageField(blank=True, null=True, upload_to='headers/commercial/')),
                ('schedule_a_site_visit', models.ImageField(blank=True, null=True, upload_to='headers/commercial/')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/commercial/')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('contacted_on', models.DateTimeField(auto_now_add=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='project.commercialproject')),
            ],
            options={
                'verbose_name_plural': '4. Commercial Enquiry',
            },
        ),
        migrations.CreateModel(
            name='CommercialConnectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectivity', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialBookingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_offers', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialBankOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bank_approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_booking_offers', to='utility.bank')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_offers', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutus', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialProjectAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_amenities', to='utility.p_amenities')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialRERAInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='overviewimage/commercial/')),
                ('registration_no', models.CharField(blank=True, max_length=50, null=True)),
                ('project_registered', models.CharField(blank=True, max_length=50, null=True)),
                ('government_rera_authorised_advertiser', models.CharField(blank=True, max_length=150, null=True)),
                ('site_address', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_us', models.CharField(blank=True, max_length=500, null=True)),
                ('disclaimer', models.CharField(blank=True, max_length=1500, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='rera_docs/commercial/')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rera', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialUSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(blank=True, max_length=150, null=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usps', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialWebSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='web_slider/commercial/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialWelcomeTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=5500, null=True)),
                ('read_more', models.TextField(blank=True, max_length=5500, null=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcomes', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialWhyInvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_invest', to='project.commercialproject')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('contacted_on', models.DateTimeField(auto_now_add=True)),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='project.residential')),
            ],
            options={
                'verbose_name_plural': '3. Residential Enquiry',
            },
        ),
    ]
