# Generated by Django 5.0.2 on 2025-07-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_alter_commercialproject_possession_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialproject',
            name='possession_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
