# Generated by Django 5.0.2 on 2025-04-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_alter_amenities_image_alter_bank_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Possession_In',
        ),
    ]
