# Generated by Django 5.0.1 on 2024-01-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color_code', models.CharField(max_length=100)),
            ],
        ),
    ]
