# Generated by Django 5.0.1 on 2024-01-26 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_social_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social_Site',
        ),
    ]
