# Generated by Django 5.0.2 on 2025-04-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_delete_possession_in'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bathroom',
        ),
        migrations.DeleteModel(
            name='Bedroom',
        ),
        migrations.DeleteModel(
            name='Bolconis',
        ),
        migrations.RemoveField(
            model_name='residential_property_type',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Commercial_Property_Type',
        ),
        migrations.DeleteModel(
            name='Residential_Property_Type',
        ),
    ]
