# Generated by Django 5.0.2 on 2025-04-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0006_delete_bathroom_delete_bedroom_delete_bolconis_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Age_Of_Properties',
        ),
        migrations.DeleteModel(
            name='Amenities',
        ),
        migrations.DeleteModel(
            name='Area_type',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
        migrations.DeleteModel(
            name='Furnishing',
        ),
        migrations.DeleteModel(
            name='Other_Room',
        ),
        migrations.DeleteModel(
            name='Parking',
        ),
        migrations.DeleteModel(
            name='Total_Floor',
        ),
    ]
