# Generated by Django 5.0.1 on 2024-01-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0007_city_commercial_property_type_locality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('icone_code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '18. Social Site',
            },
        ),
        migrations.AlterModelOptions(
            name='age_of_properties',
            options={'verbose_name_plural': '13. Age Of Properties'},
        ),
        migrations.AlterModelOptions(
            name='amenities',
            options={'verbose_name_plural': '04. Amenities'},
        ),
        migrations.AlterModelOptions(
            name='area_type',
            options={'verbose_name_plural': '15. Area_type'},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name_plural': '03. Bank'},
        ),
        migrations.AlterModelOptions(
            name='bathroom',
            options={'verbose_name_plural': '06. Bathroom'},
        ),
        migrations.AlterModelOptions(
            name='bedroom',
            options={'verbose_name_plural': '05. Bedroom'},
        ),
        migrations.AlterModelOptions(
            name='bolconis',
            options={'verbose_name_plural': '07. Bolconis'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': '17. City'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': '16. Colors'},
        ),
        migrations.AlterModelOptions(
            name='commercial_property_type',
            options={'verbose_name_plural': '02. Commercial Property Type'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name_plural': '11. Floor'},
        ),
        migrations.AlterModelOptions(
            name='furnishing',
            options={'verbose_name_plural': '09. Furnishing'},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name_plural': '17. Locality'},
        ),
        migrations.AlterModelOptions(
            name='other_room',
            options={'verbose_name_plural': '08. Other Room'},
        ),
        migrations.AlterModelOptions(
            name='parking',
            options={'verbose_name_plural': '10. Parking'},
        ),
        migrations.AlterModelOptions(
            name='possession_in',
            options={'verbose_name_plural': '14. Possession In'},
        ),
        migrations.AlterModelOptions(
            name='residential_property_type',
            options={'verbose_name_plural': '01. Residential Property Type'},
        ),
        migrations.AlterModelOptions(
            name='total_floor',
            options={'verbose_name_plural': '12. Total Flooe'},
        ),
        migrations.AlterModelOptions(
            name='willing_to_rent_out',
            options={'verbose_name_plural': '12. Willing To Rent Out'},
        ),
    ]
