# Generated by Django 5.0.2 on 2025-06-27 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0008_user_status_visit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locality',
            name='image',
        ),
    ]
