# Generated by Django 5.0.2 on 2025-06-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0009_remove_locality_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='amenities/')),
            ],
        ),
    ]
