# Generated by Django 5.0.2 on 2025-07-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0011_remove_locality_featured_locality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
