# Generated by Django 5.0.2 on 2025-07-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0012_visit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Possession_In',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': '21. Possession Years',
            },
        ),
    ]
