# Generated by Django 5.0.2 on 2025-07-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0013_possession_in'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Possession_In',
        ),
    ]
