# Generated by Django 5.0.2 on 2025-07-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0015_locality_featured_city_locality_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locality',
            old_name='featured_city',
            new_name='featured_locality',
        ),
    ]
