# Generated by Django 5.0.1 on 2024-01-27 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('utility', '0007_city_commercial_property_type_locality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='featured_builder',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='locality',
        ),
        migrations.AlterField(
            model_name='developer',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('featured_builder', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.city')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.locality')),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user_info')),
            ],
        ),
        migrations.AddField(
            model_name='developer',
            name='user_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user_info'),
        ),
    ]
