# Generated by Django 5.0.1 on 2024-01-27 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_developer_address_remove_developer_city_and_more'),
        ('utility', '0007_city_commercial_property_type_locality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='user_info',
        ),
        migrations.AddField(
            model_name='developer',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.city'),
        ),
        migrations.AddField(
            model_name='developer',
            name='contact_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='featured_builder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='developer',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='developer',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.locality'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='User_Info',
        ),
    ]
