# Generated by Django 5.0.2 on 2025-07-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_ownerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnerProfile',
        ),
    ]
