# Generated by Django 5.0.2 on 2025-04-17 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sell_property',
            options={'verbose_name_plural': '1. Sell Property'},
        ),
    ]
