# Generated by Django 5.0.2 on 2025-04-18 05:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_rename_sell_property_selly_and_more'),
        ('utility', '0004_alter_amenities_image_alter_bank_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Selly',
            new_name='Sell',
        ),
        migrations.RenameModel(
            old_name='Selly_Comment',
            new_name='Sell_Comment',
        ),
        migrations.RenameModel(
            old_name='Selly_Images',
            new_name='Sell_Images',
        ),
    ]
