# Generated by Django 5.0.2 on 2025-04-18 05:21

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_rename_selly_sell_rename_selly_comment_sell_comment_and_more'),
        ('utility', '0004_alter_amenities_image_alter_bank_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Ready to move offices', 'Ready to move offices'), ('Shops & Retail', 'Shops & Retail'), ('Agricultural/Farm Land', 'Agricultural/Farm Land'), ('Industrial Land/Plots', 'Industrial Land/Plots'), ('Warehouse', 'Warehouse'), ('Factory & Manufacturing', 'Factory & Manufacturing'), ('Bare shell offices', 'Bare shell offices'), ('Commercial/Inst. Land', 'Commercial/Inst. Land'), ('Cold Storage', 'Cold Storage'), ('Hotel/Resorts', 'Hotel/Resorts')], max_length=55)),
                ('title', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=255)),
                ('meta_description', models.CharField(max_length=255)),
                ('min_price', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('max_price', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('min_area', models.CharField(blank=True, max_length=50, null=True)),
                ('max_area', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=15000, null=True)),
                ('project_size', models.CharField(blank=True, max_length=255, null=True)),
                ('possession', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('featured_property', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=55, null=True)),
                ('slug', models.SlugField(blank=True, max_length=555, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('amenities', models.ManyToManyField(blank=True, to='utility.amenities')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.city')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.locality')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='commercial.lease')),
            ],
            options={
                'verbose_name_plural': '1. Lease Property',
            },
        ),
        migrations.CreateModel(
            name='Lease_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('rate', models.IntegerField(default=1)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='New', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.lease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '3. Residential Comment',
            },
        ),
        migrations.CreateModel(
            name='Lease_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.lease')),
            ],
            options={
                'verbose_name_plural': '5. Residential Project Images',
            },
        ),
    ]
