# Generated by Django 5.0.2 on 2025-04-18 19:11

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_lease_lease_comment_lease_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='amenities',
        ),
        migrations.AddField(
            model_name='lease',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Air Condition', 'Air Condition'), ('Badminton Court', 'Badminton Court'), ('balcony', 'balcony'), ('Barbeque', 'Barbeque'), ('Basket Ball', 'Basket Ball'), ('Car Parking', 'Car Parking'), ('CCTV', 'CCTV'), ('club house', 'club house'), ('Community hall', 'Community hall'), ('Conference room', 'Conference room'), ('Creche Area', 'Creche Area'), ('Cricket Pitch', 'Cricket Pitch'), ('Curtains', 'Curtains'), ('Dining Table', 'Dining Table'), ('Electric Vehicle Charging Socket', 'Electric Vehicle Charging Socket'), ('Electrical Switchboard', 'Electrical Switchboard'), ('Elevator', 'Elevator'), ('Exhaust Fan', 'Exhaust Fan'), ('Fans', 'Fans'), ('Fire Fighting Equipment', 'Fire Fighting Equipment'), ('Garden', 'Garden'), ('Geysers', 'Geysers'), ('Grand lobby', 'Grand lobby'), ('Gymnasium', 'Gymnasium'), ('Hammock', 'Hammock'), ('Indoor Games', 'Indoor Games'), ('Intercom', 'Intercom'), ('jacuzzi', 'jacuzzi'), ('Jogging track', 'Jogging track'), ('Kids Play Area', 'Kids Play Area'), ('Library', 'Library'), ('Lights', 'Lights'), ('Live chess', 'Live chess'), ('Microwave', 'Microwave'), ('mini theater', 'mini theater'), ('Modular Kitchen', 'Modular Kitchen'), ('Multipurpose Hall', 'Multipurpose Hall'), ('Rain Water Harvesting', 'Rain Water Harvesting'), ('Reflexology Path', 'Reflexology Path'), ('Refrigerator', 'Refrigerator'), ('Regular Water Supply', 'Regular Water Supply'), ('Rooftop garden', 'Rooftop garden'), ('sauna bath', 'sauna bath'), ('Security', 'Security'), ('Senior citizen area', 'Senior citizen area'), ('Society Office', 'Society Office'), ('Sofa', 'Sofa'), ('Solar Power', 'Solar Power'), ('Spa', 'Spa'), ('Squash court', 'Squash court'), ('Stainless Steel Sink', 'Stainless Steel Sink'), ('Stove', 'Stove'), ('Swimming Pool', 'Swimming Pool'), ('Terrace', 'Terrace'), ('Video Door phone', 'Video Door phone'), ('Volleyball Court', 'Volleyball Court'), ('Wardrobe T.V', 'Wardrobe T.V'), ('Washing Machine', 'Washing Machine'), ('Water Purifier', 'Water Purifier'), ('Water Softener', 'Water Softener'), ('Wi fi', 'Wi fi'), ('yoga deck', 'yoga deck')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Air Condition', 'Air Condition'), ('Badminton Court', 'Badminton Court'), ('balcony', 'balcony'), ('Barbeque', 'Barbeque'), ('Basket Ball', 'Basket Ball'), ('Car Parking', 'Car Parking'), ('CCTV', 'CCTV'), ('club house', 'club house'), ('Community hall', 'Community hall'), ('Conference room', 'Conference room'), ('Creche Area', 'Creche Area'), ('Cricket Pitch', 'Cricket Pitch'), ('Curtains', 'Curtains'), ('Dining Table', 'Dining Table'), ('Electric Vehicle Charging Socket', 'Electric Vehicle Charging Socket'), ('Electrical Switchboard', 'Electrical Switchboard'), ('Elevator', 'Elevator'), ('Exhaust Fan', 'Exhaust Fan'), ('Fans', 'Fans'), ('Fire Fighting Equipment', 'Fire Fighting Equipment'), ('Garden', 'Garden'), ('Geysers', 'Geysers'), ('Grand lobby', 'Grand lobby'), ('Gymnasium', 'Gymnasium'), ('Hammock', 'Hammock'), ('Indoor Games', 'Indoor Games'), ('Intercom', 'Intercom'), ('jacuzzi', 'jacuzzi'), ('Jogging track', 'Jogging track'), ('Kids Play Area', 'Kids Play Area'), ('Library', 'Library'), ('Lights', 'Lights'), ('Live chess', 'Live chess'), ('Microwave', 'Microwave'), ('mini theater', 'mini theater'), ('Modular Kitchen', 'Modular Kitchen'), ('Multipurpose Hall', 'Multipurpose Hall'), ('Rain Water Harvesting', 'Rain Water Harvesting'), ('Reflexology Path', 'Reflexology Path'), ('Refrigerator', 'Refrigerator'), ('Regular Water Supply', 'Regular Water Supply'), ('Rooftop garden', 'Rooftop garden'), ('sauna bath', 'sauna bath'), ('Security', 'Security'), ('Senior citizen area', 'Senior citizen area'), ('Society Office', 'Society Office'), ('Sofa', 'Sofa'), ('Solar Power', 'Solar Power'), ('Spa', 'Spa'), ('Squash court', 'Squash court'), ('Stainless Steel Sink', 'Stainless Steel Sink'), ('Stove', 'Stove'), ('Swimming Pool', 'Swimming Pool'), ('Terrace', 'Terrace'), ('Video Door phone', 'Video Door phone'), ('Volleyball Court', 'Volleyball Court'), ('Wardrobe T.V', 'Wardrobe T.V'), ('Washing Machine', 'Washing Machine'), ('Water Purifier', 'Water Purifier'), ('Water Softener', 'Water Softener'), ('Wi fi', 'Wi fi'), ('yoga deck', 'yoga deck')], max_length=50, null=True),
        ),
    ]
